version: '3.9'

services:
  qdrant:
    image: qdrant/qdrant:v1.9.2 
    container_name: qdrant
    ports:
      - "6333:6333"  # REST
      - "6334:6334"  # gRPC
    volumes:
      - ./qdrant_storage:/qdrant/storage
    restart: unless-stopped
